# Site settings
title: BEST
email: best@gobaci.com
description: > # this means to ignore newlines until "baseurl:"
  © BEST 2015. All rights reserved
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
gitstatic: "https://BACI-Employment.github.io"
twitter_username: gobaci 
github_username: burnabyassociation

# Build settings
markdown: kramdown
